# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-03
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - Added docstrings
# Comments:
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel
from db.session import get_db

router = APIRouter(prefix="/chat", tags=["chat"])


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None


@router.post("")
async def chat(request: ChatRequest, db: AsyncSession = Depends(get_db)):
    """Accept a chat message and return an AI response. RAG + LLM not yet implemented."""
    # TODO: RAG retrieval + Gemini/Azure OpenAI streaming response
    return {"response": "Chatbot not yet implemented", "session_id": request.session_id}


@router.get("/history")
async def chat_history(session_id: str, db: AsyncSession = Depends(get_db)):
    """Return chat message history for a session."""
    # TODO: retrieve from chat_messages table
    return {"messages": []}
