# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - None
# Comments: None
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
import os
from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel
from google import genai
from db.session import get_db
from chatbot.context import build_chat_context, CHAT_SYSTEM

router = APIRouter(prefix="/chat", tags=["chat"])

_gemini_client = None


def _get_client():
    """Return a cached Gemini client."""
    global _gemini_client
    if _gemini_client is None:
        _gemini_client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    return _gemini_client


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None
    history: list[dict] | None = None
    population: int = 10_000


@router.post("")
async def chat(request: ChatRequest, db: AsyncSession = Depends(get_db)):
    """Accept a chat message, build DB context, and return a Gemini response."""
    context = await build_chat_context(db, population=request.population)
    system_text = CHAT_SYSTEM.format(context=context)

    # Build conversation including history
    history = request.history or []
    conversation = []
    for h in history[-8:]:
        role = "Executive" if h.get("role") == "user" else "Averin AI"
        conversation.append(f"{role}: {h.get('content', '')}")
    conversation.append(f"Executive: {request.message}")
    conversation.append("Averin AI:")

    full_prompt = system_text + "\n\n--- CONVERSATION ---\n" + "\n".join(conversation)

    try:
        client = _get_client()
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite",
            contents=full_prompt,
        )
        return {"response": response.text.strip(), "session_id": request.session_id}
    except Exception as e:
        return {"response": f"Sorry, I encountered an error: {str(e)}", "session_id": request.session_id}


@router.get("/history")
async def chat_history(session_id: str, db: AsyncSession = Depends(get_db)):
    """Return chat message history for a session."""
    # TODO: persist history to chat_messages table
    return {"messages": []}
