# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-03
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - Added docstrings
# Comments:
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------

from fastapi import APIRouter, BackgroundTasks
from ehr.metrics import compute_all
from ehr.gaps import run_gap_computation
from db.session import AsyncSessionLocal
from datetime import datetime

router = APIRouter(prefix="/ehr", tags=["ehr"])

_sync_state: dict = {"status": "idle", "last_sync": None, "last_results": None, "gap_summary": None}


async def _run_sync():
    """Run the full EHR sync pipeline: FHIR metric computation → gap computation → DB write."""
    _sync_state["status"] = "running"
    try:
        results = await compute_all()
        _sync_state["last_results"] = results

        async with AsyncSessionLocal() as db:
            gap_summary = await run_gap_computation(db, results)
            _sync_state["gap_summary"] = gap_summary

        _sync_state["status"] = "complete"
        _sync_state["last_sync"] = datetime.utcnow().isoformat()
    except Exception as e:
        _sync_state["status"] = "failed"
        _sync_state["error"] = str(e)


@router.post("/sync")
async def trigger_sync(background_tasks: BackgroundTasks):
    """Trigger an async EHR sync. Returns immediately; check /sync/status for progress."""
    if _sync_state["status"] == "running":
        return {"status": "already_running"}
    background_tasks.add_task(_run_sync)
    return {"status": "queued"}


@router.get("/sync/status")
async def sync_status():
    """Return current sync state including status, last run time, and any errors."""
    return _sync_state


@router.get("/sync/results")
async def sync_results():
    """Return raw FHIR metric rates from the last completed sync."""
    return _sync_state.get("last_results", {})


@router.get("/sync/gaps")
async def sync_gaps():
    """Return per-payer gap summary from the last completed sync."""
    return _sync_state.get("gap_summary", {})
