# -----------------------------------------------------------
# AI-GENERATED CODE — HUMAN REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-03
#
# Human reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - None
# Comments: None
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from api.contracts import router as contracts_router
from api.payers import router as payers_router
from api.ehr import router as ehr_router
from api.chat import router as chat_router
import os

app = FastAPI(title="Averin Health API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(contracts_router)
app.include_router(payers_router)
app.include_router(ehr_router)
app.include_router(chat_router)

# Serve frontend static files and HTML if directories are mounted
_static_dir = "/static"
_templates_dir = "/templates"

if os.path.isdir(_static_dir):
    app.mount("/static", StaticFiles(directory=_static_dir), name="static")

@app.get("/health")
async def health():
    """API health check."""
    return {"status": "ok"}

@app.get("/")
async def index():
    """Serve the frontend dashboard."""
    return FileResponse(f"{_templates_dir}/index.html")

@app.get("/demo-contracts/{filename}")
async def demo_contract(filename: str):
    """Serve a demo contract PDF for the beta sample loader."""
    allowed = {"contract_aetna.pdf", "contract_humana.pdf", "contract_unitedhealth.pdf", "contract_meridian.pdf"}
    if filename not in allowed:
        raise HTTPException(status_code=404, detail="Demo contract not found")
    return FileResponse(f"/contracts/{filename}", media_type="application/pdf")
