# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - None
# Comments: None
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
"""Shared pytest fixtures and configuration."""

import os
import sys
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))

CONTRACTS_DIR = os.path.join(os.path.dirname(__file__), "..", "contracts")


def pytest_configure(config):
    config.addinivalue_line(
        "markers", "integration: marks tests that call external services (Azure, Gemini)"
    )


def _load_pdf(filename: str) -> bytes:
    path = os.path.join(CONTRACTS_DIR, filename)
    with open(path, "rb") as f:
        return f.read()


def _has_azure_creds() -> bool:
    return bool(
        os.environ.get("AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT")
        and os.environ.get("AZURE_DOCUMENT_INTELLIGENCE_KEY")
        and os.environ.get("GEMINI_API_KEY")
    )


skip_if_no_creds = pytest.mark.skipif(
    not _has_azure_creds(),
    reason="Azure Document Intelligence and Gemini credentials not set",
)


@pytest.fixture(scope="session")
def aetna_metrics():
    """Extract metrics from Aetna contract — cached for the session."""
    from extraction.pipeline import extract_text_from_pdf, extract_metrics_with_llm
    pdf = _load_pdf("contract_aetna.pdf")
    text = extract_text_from_pdf(pdf)
    return extract_metrics_with_llm(text)


@pytest.fixture(scope="session")
def meridian_metrics():
    """Extract metrics from Meridian contract — cached for the session."""
    from extraction.pipeline import extract_text_from_pdf, extract_metrics_with_llm
    pdf = _load_pdf("contract_meridian.pdf")
    text = extract_text_from_pdf(pdf)
    return extract_metrics_with_llm(text)
