# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - None
# Comments: None
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
"""
Integration tests for contract extraction quality.

Calls real Azure Document Intelligence + Gemini against known contracts.
Ground truth is manually verified against the source PDFs.

Run with: docker-compose exec api python -m pytest /tests/test_extraction.py -v -m integration
Skip in CI: pytest -m "not integration"
"""

import pytest

VALID_OPERATORS = {">=", ">", "<=", "<", "="}


def _find(metrics: list[dict], name_fragment: str) -> dict | None:
    """Find a metric by case-insensitive name fragment."""
    return next(
        (m for m in metrics if name_fragment.lower() in m.get("metric_name", "").lower()),
        None,
    )


# ── Aetna ─────────────────────────────────────────────────────────────────────

@pytest.mark.integration
class TestAetnaExtraction:
    """Ground truth: contract_aetna.pdf — manually verified."""

    def test_minimum_metric_count(self, aetna_metrics):
        assert len(aetna_metrics) >= 7, f"Expected >=7 metrics, got {len(aetna_metrics)}"

    def test_a1c_control_extracted(self, aetna_metrics):
        m = _find(aetna_metrics, "A1C Control")
        assert m is not None, "Diabetes A1C Control metric not found"

    def test_a1c_control_target(self, aetna_metrics):
        m = _find(aetna_metrics, "A1C Control")
        assert m["target_value"] == 55.0, f"Expected 55.0, got {m['target_value']}"
        assert m["target_operator"] == ">="

    def test_bp_control_extracted(self, aetna_metrics):
        m = _find(aetna_metrics, "Blood Pressure") or _find(aetna_metrics, "BP Control")
        assert m is not None, "Hypertension BP Control metric not found"

    def test_bp_control_target(self, aetna_metrics):
        m = _find(aetna_metrics, "Blood Pressure") or _find(aetna_metrics, "BP Control")
        assert m["target_value"] == 70.0, f"Expected 70.0, got {m['target_value']}"
        assert m["target_operator"] == ">="

    def test_ed_utilization_extracted(self, aetna_metrics):
        m = _find(aetna_metrics, "Emergency Department") or _find(aetna_metrics, "ED")
        assert m is not None, "ED Utilization metric not found"

    def test_ed_utilization_operator(self, aetna_metrics):
        """ED utilization is lower-is-better — must have <= operator."""
        m = _find(aetna_metrics, "Emergency Department") or _find(aetna_metrics, "ED")
        assert m["target_operator"] == "<=", f"Expected <=, got {m['target_operator']}"

    def test_readmission_operator(self, aetna_metrics):
        """Readmission rate is lower-is-better — must have <= operator."""
        m = _find(aetna_metrics, "Readmission")
        assert m is not None, "Readmission metric not found"
        assert m["target_operator"] == "<="

    def test_no_null_metric_names(self, aetna_metrics):
        for m in aetna_metrics:
            assert m.get("metric_name"), "Found metric with null/empty metric_name"

    def test_all_operators_valid(self, aetna_metrics):
        for m in aetna_metrics:
            op = m.get("target_operator")
            if op is not None:
                assert op in VALID_OPERATORS, f"Invalid operator '{op}' on {m.get('metric_name')}"

    def test_all_target_values_numeric(self, aetna_metrics):
        for m in aetna_metrics:
            tv = m.get("target_value")
            if tv is not None:
                assert isinstance(tv, (int, float)), \
                    f"Non-numeric target_value '{tv}' on {m.get('metric_name')}"

    def test_source_text_present(self, aetna_metrics):
        missing = [m.get("metric_name") for m in aetna_metrics if not m.get("source_text")]
        assert not missing, f"Missing source_text on: {missing}"


# ── Meridian (edge cases) ──────────────────────────────────────────────────────

@pytest.mark.integration
class TestMeridianEdgeCases:
    """Ground truth: contract_meridian.pdf — designed to test extraction edge cases."""

    def test_quality_withhold_threshold_extracted(self, meridian_metrics):
        """Withhold threshold (75%) must appear somewhere in the extraction — as a metric
        target value or in source/calculation text. LLMs may structure this differently."""
        has_75_target = any(m.get("target_value") == 75.0 for m in meridian_metrics)
        has_75_in_text = any(
            "75" in str(m.get("source_text", "")) or "75" in str(m.get("calculation_method", ""))
            for m in meridian_metrics
        )
        assert has_75_target or has_75_in_text, \
            "Quality withhold threshold of 75% not found in any extracted metric"

    def test_composite_diabetes_measure_extracted(self, meridian_metrics):
        """Composite measure (A1C + eye exam in one clause) must be extracted."""
        m = _find(meridian_metrics, "Diabetes")
        assert m is not None, "Composite diabetes measure not extracted"

    def test_hypertension_extracted(self, meridian_metrics):
        """Reference-only HEDIS measure must be extracted even without explicit target."""
        m = _find(meridian_metrics, "Hypertension") or _find(meridian_metrics, "Blood Pressure")
        assert m is not None, "Hypertension measure not extracted"

    def test_minimum_metric_count(self, meridian_metrics):
        assert len(meridian_metrics) >= 4, \
            f"Expected >=4 metrics from Meridian, got {len(meridian_metrics)}"

    def test_no_hallucinated_targets(self, meridian_metrics):
        """Metrics defined only by reference should have null target_value, not fabricated numbers."""
        for m in meridian_metrics:
            tv = m.get("target_value")
            if tv is not None:
                assert isinstance(tv, (int, float)), \
                    f"Non-numeric target_value '{tv}' on {m.get('metric_name')}"
                assert 0 <= tv <= 200, \
                    f"Implausible target_value {tv} on {m.get('metric_name')} — possible hallucination"


# ── Schema ─────────────────────────────────────────────────────────────────────

@pytest.mark.integration
class TestExtractionSchema:
    """All extractions must conform to the expected JSON schema regardless of contract."""

    def test_aetna_required_fields(self, aetna_metrics):
        for m in aetna_metrics:
            assert "metric_name" in m, f"Missing metric_name: {m}"
            assert "target_operator" in m, f"Missing target_operator: {m}"

    def test_meridian_required_fields(self, meridian_metrics):
        for m in meridian_metrics:
            assert "metric_name" in m, f"Missing metric_name: {m}"
            assert "target_operator" in m, f"Missing target_operator: {m}"
