# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - None
# Comments: None
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
"""
Unit tests for gap computation math.

No DB or FHIR dependencies — tests the pure functions in ehr/gaps.py.
These must pass before any gap data is shown to users.
"""

import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))

from ehr.gaps import compute_gap, compute_status, compute_opportunity_dollars


class TestComputeGap:
    """compute_gap returns signed pp distance from target. Negative = failing."""

    def test_ge_operator_on_track(self):
        assert compute_gap(70.0, ">=", 75.0) == 5.0

    def test_ge_operator_failing(self):
        assert compute_gap(70.0, ">=", 60.0) == -10.0

    def test_ge_operator_exactly_at_target(self):
        assert compute_gap(70.0, ">=", 70.0) == 0.0

    def test_le_operator_on_track(self):
        """Lower-is-better metric (e.g. readmission). On track = positive gap."""
        assert compute_gap(12.0, "<=", 8.0) == 4.0

    def test_le_operator_failing(self):
        """ED utilization above target = failing = negative gap."""
        assert compute_gap(45.0, "<=", 70.0) == -25.0

    def test_le_operator_exactly_at_target(self):
        assert compute_gap(45.0, "<=", 45.0) == 0.0

    def test_rounding(self):
        assert compute_gap(70.0, ">=", 62.333) == -7.67


class TestComputeStatus:
    """Status thresholds: on_track (gap>=0), at_risk (-10 to 0), failing (<-10)."""

    def test_on_track(self):
        assert compute_status(5.0, ">=") == "on_track"

    def test_at_target(self):
        assert compute_status(0.0, ">=") == "on_track"

    def test_at_risk(self):
        assert compute_status(-5.0, ">=") == "at_risk"

    def test_at_risk_boundary(self):
        assert compute_status(-10.0, ">=") == "at_risk"

    def test_failing(self):
        assert compute_status(-11.0, ">=") == "failing"

    def test_failing_large_gap(self):
        assert compute_status(-50.0, ">=") == "failing"

    def test_le_on_track(self):
        assert compute_status(4.0, "<=") == "on_track"

    def test_le_at_risk(self):
        assert compute_status(-10.0, "<=") == "at_risk"

    def test_le_failing(self):
        assert compute_status(-16.0, "<=") == "failing"


class TestComputeOpportunityDollars:
    """Opportunity $ = 0 when on track, positive when failing."""

    def test_on_track_returns_zero(self):
        assert compute_opportunity_dollars(5.0, 100, None, None) == 0.0

    def test_at_target_returns_zero(self):
        assert compute_opportunity_dollars(0.0, 100, None, None) == 0.0

    def test_uses_financial_weight_when_provided(self):
        # gap=-10pp, 100 patients, $5/patient/pp → $5,000
        result = compute_opportunity_dollars(-10.0, 100, 5.0, None)
        assert result == 5000.0

    def test_quality_bonus_default(self):
        # gap=-10pp, 100 patients, $50/patient/pp default → $50,000
        result = compute_opportunity_dollars(-10.0, 100, None, "quality_bonus")
        assert result == 50000.0

    def test_quality_withhold_default(self):
        # gap=-10pp, 100 patients, $30/patient/pp default → $30,000
        result = compute_opportunity_dollars(-10.0, 100, None, "quality_withhold")
        assert result == 30000.0

    def test_unknown_payment_model_uses_fallback(self):
        # $40/patient/pp fallback
        result = compute_opportunity_dollars(-10.0, 100, None, None)
        assert result == 40000.0

    def test_financial_weight_takes_priority_over_payment_model(self):
        result = compute_opportunity_dollars(-10.0, 100, 2.0, "quality_bonus")
        assert result == 2000.0

    def test_zero_denominator(self):
        result = compute_opportunity_dollars(-10.0, 0, None, None)
        assert result == 0.0

    def test_large_gap_negotiate_threshold(self):
        """A gap of -31pp should still compute correctly regardless of NEGOTIATE flag."""
        result = compute_opportunity_dollars(-31.0, 100, None, "quality_bonus")
        assert result == 155000.0
