# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: _______________
# Changes made during review:
#   -
# Comments:
#
# Sign-off: _______________
# -----------------------------------------------------------
"""Add metric_mappings table and seed with initial patterns.

Revision ID: 20260604_metric_mappings
Revises: 001
Create Date: 2026-06-04
"""
from alembic import op
import sqlalchemy as sa

revision = "20260604_metric_mappings"
down_revision = "001"
branch_labels = None
depends_on = None

# Each row: (pattern, performance_key, match_type, priority)
SEED_MAPPINGS = [
    # Diabetes
    ("a1c",                         "diabetes_a1c_control",      "contains", 20),
    ("hba1c",                       "diabetes_a1c_control",      "contains", 20),
    ("glycemic",                    "diabetes_a1c_control",      "contains", 20),
    ("glycated hemoglobin",         "diabetes_a1c_control",      "contains", 20),
    ("hemoglobin a1",               "diabetes_a1c_control",      "contains", 20),
    ("diabetes control",            "diabetes_a1c_control",      "contains", 15),

    # Hypertension / Blood Pressure
    ("blood pressure control",      "bp_control",                "contains", 20),
    ("bp control",                  "bp_control",                "contains", 20),
    ("controlling high blood",      "bp_control",                "contains", 20),
    ("hypertension control",        "bp_control",                "contains", 20),

    # Breast Cancer Screening
    ("breast cancer",               "breast_cancer_screening",   "contains", 20),
    ("mammogram",                   "breast_cancer_screening",   "contains", 20),
    ("mammography",                 "breast_cancer_screening",   "contains", 20),
    ("bcs",                         "breast_cancer_screening",   "contains", 10),

    # Colorectal Screening
    ("colorectal",                  "colorectal_screening",      "contains", 20),
    ("colonoscopy",                 "colorectal_screening",      "contains", 20),
    ("colon cancer",                "colorectal_screening",      "contains", 20),
    ("crc",                         "colorectal_screening",      "contains", 10),

    # Cervical Screening
    ("cervical",                    "cervical_screening",        "contains", 20),
    ("pap smear",                   "cervical_screening",        "contains", 20),
    ("pap test",                    "cervical_screening",        "contains", 20),

    # Annual Wellness Visit
    ("wellness visit",              "annual_wellness_visit",     "contains", 20),
    ("annual wellness",             "annual_wellness_visit",     "contains", 20),
    ("preventive visit",            "annual_wellness_visit",     "contains", 15),
    ("awv",                         "annual_wellness_visit",     "contains", 10),

    # Depression Screening
    ("depression screen",           "depression_screening",      "contains", 20),
    ("phq-9",                       "depression_screening",      "contains", 20),
    ("phq9",                        "depression_screening",      "contains", 20),
    ("behavioral health screen",    "depression_screening",      "contains", 15),
    ("mental health screen",        "depression_screening",      "contains", 15),

    # Medication Adherence
    ("med adherence diabetes",      "med_adherence_diabetes",    "contains", 25),
    ("medication adherence diabet", "med_adherence_diabetes",    "contains", 25),
    ("med adherence hypertension",  "med_adherence_hypertension","contains", 25),
    ("med adherence statin",        "med_adherence_statin",      "contains", 25),
    ("proportion days covered",     "med_adherence_diabetes",    "contains", 10),
    ("pdc",                         "med_adherence_diabetes",    "contains", 5),

    # Statin Therapy
    ("statin therapy",              "statin_therapy",            "contains", 20),
    ("statin use",                  "statin_therapy",            "contains", 20),
    ("ldl",                         "statin_therapy",            "contains", 10),
    ("cholesterol therapy",         "statin_therapy",            "contains", 15),

    # Readmission
    ("readmission",                 "readmission_rate",          "contains", 20),
    ("readmit",                     "readmission_rate",          "contains", 20),
    ("30-day",                      "readmission_rate",          "contains", 10),

    # ED Utilization
    ("emergency department",        "ed_utilization",            "contains", 20),
    ("ed visit",                    "ed_utilization",            "contains", 20),
    ("ed utilization",              "ed_utilization",            "contains", 20),
    ("er visit",                    "ed_utilization",            "contains", 20),

    # Tobacco
    ("tobacco",                     "tobacco_screening",         "contains", 20),
    ("smoking",                     "tobacco_screening",         "contains", 20),
    ("nicotine",                    "tobacco_screening",         "contains", 20),

    # BMI
    ("bmi",                         "bmi_screening",             "contains", 20),
    ("body mass index",             "bmi_screening",             "contains", 20),

    # Asthma
    ("asthma",                      "asthma_medication_ratio",   "contains", 20),

    # Care Coordination / Transitions
    ("transitions of care",         "transitions_of_care",       "contains", 20),
    ("transition of care",          "transitions_of_care",       "contains", 20),
    ("care coordination",           "transitions_of_care",       "contains", 15),
    ("follow-up",                   "transitions_of_care",       "contains", 5),
]


def upgrade():
    """Create metric_mappings table and seed with initial patterns."""
    op.create_table(
        "metric_mappings",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("pattern", sa.String(255), nullable=False),
        sa.Column("performance_key", sa.String(100), nullable=False),
        sa.Column("match_type", sa.String(20), nullable=False, server_default="contains"),
        sa.Column("priority", sa.Integer, nullable=False, server_default="10"),
        sa.Column("active", sa.Boolean, nullable=False, server_default="true"),
    )

    op.bulk_insert(
        sa.table(
            "metric_mappings",
            sa.column("pattern", sa.String),
            sa.column("performance_key", sa.String),
            sa.column("match_type", sa.String),
            sa.column("priority", sa.Integer),
            sa.column("active", sa.Boolean),
        ),
        [
            {"pattern": p, "performance_key": k, "match_type": m, "priority": pr, "active": True}
            for p, k, m, pr in SEED_MAPPINGS
        ],
    )


def downgrade():
    """Drop metric_mappings table."""
    op.drop_table("metric_mappings")
