# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date:  2026-06-04
# Changes made during review:
#   - None
# Comments: None
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
"""Chatbot context builder and system prompt.

Builds a PHI-free text summary of payer performance for the LLM context window.
Only aggregated rates and counts — no patient identifiers ever enter this layer.
"""

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from models import Contract, Metric, PerformanceGap

CHAT_SYSTEM = """You are Averin Insight™ — an AI assistant embedded in a value-based care analytics platform used by hospital executives.

{context}

Your role: Help medical directors and C-suite executives understand their VBC contract performance, prioritize improvement opportunities, and prepare for payer negotiations.

Guidelines:
- Lead with the most important insight — executives are busy
- Always reference specific numbers, metric names, and gaps from the context above
- Explain clinical concepts in plain business language (these are NOT clinicians)
- When asked about improvement, give 2-3 specific, actionable steps
- When discussing financial impact, be specific about the dollar figures in context
- Be confident, direct, and concise — no filler phrases
- Never fabricate numbers not present in the context
- If asked about a metric with no data, say so clearly rather than guessing
"""


def _scale(dollars: float, denominator: int, population: int) -> float:
    """Scale raw opportunity dollars from test population to real population size."""
    if not dollars or not denominator:
        return 0.0
    return dollars * (population / denominator)


def _fmt(dollars: float) -> str:
    if dollars >= 1_000_000:
        return f"${dollars/1_000_000:.1f}M"
    if dollars >= 1_000:
        return f"${dollars/1_000:.0f}K"
    return f"${dollars:,.0f}"


async def build_chat_context(db: AsyncSession, population: int = 10_000) -> str:
    """Query DB and build a PHI-free performance summary for the LLM context window.

    population: attributed member count used to scale opportunity dollars,
                matching what the UI shows. Defaults to 10,000.
    """
    contracts_result = await db.execute(
        select(Contract).order_by(Contract.payer_name)
    )
    contracts = contracts_result.scalars().all()

    if not contracts:
        return "No contracts have been loaded yet."

    lines = [
        f"CURRENT PERFORMANCE DATA BY PAYER (opportunity $ scaled to {population:,} attributed members):"
    ]
    total_opportunity = 0.0

    for contract in contracts:
        metrics_result = await db.execute(
            select(Metric, PerformanceGap)
            .outerjoin(PerformanceGap, PerformanceGap.metric_id == Metric.id)
            .where(Metric.contract_id == contract.id)
        )
        rows = metrics_result.all()
        if not rows:
            continue

        payer_opportunity = sum(
            _scale(g.opportunity_dollars or 0, g.denominator_count or 1, population)
            for _, g in rows if g
        )
        total_opportunity += payer_opportunity

        lines.append(f"\nPAYER: {contract.payer_name}")
        lines.append(f"  Payment model: {contract.payment_model or 'not specified'}")
        lines.append(f"  Total opportunity: {_fmt(payer_opportunity)}")
        lines.append("  Metrics:")

        for metric, gap in rows:
            if gap and gap.rate is not None:
                scaled_opp = _scale(gap.opportunity_dollars or 0, gap.denominator_count or 1, population)
                status_str = gap.status or "unknown"
                flag_str = f" [{gap.opportunity_flag}]" if gap.opportunity_flag else ""
                opp_str = f" {_fmt(scaled_opp)} opportunity" if scaled_opp else ""
                lines.append(
                    f"    - {metric.measure_name}: "
                    f"target {metric.target_operator or '>='}{metric.target_value or '?'}%, "
                    f"actual {gap.rate}% "
                    f"({gap.numerator_count} of {gap.denominator_count} patients in test data), "
                    f"gap {gap.gap_pp:+.1f}pp — {status_str}{flag_str}{opp_str}"
                )
            else:
                lines.append(
                    f"    - {metric.measure_name}: "
                    f"target {metric.target_operator or '>='}{metric.target_value or '?'}% "
                    f"— no EHR data yet"
                )

    lines.append(f"\nTOTAL OPPORTUNITY ACROSS ALL PAYERS: {_fmt(total_opportunity)}")
    return "\n".join(lines)
