# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: _______________
# Changes made during review:
#   -
# Comments:
#
# Sign-off: _______________
# -----------------------------------------------------------
"""FHIR R4 client for Azure Health Data Services.

Uses OAuth2 client credentials flow — no username/password.
Token is cached and refreshed automatically.
"""

import os
import time
import httpx
from typing import Any

FHIR_BASE = os.environ.get("AZURE_FHIR_URL", "").rstrip("/")
TENANT_ID = os.environ.get("AZURE_FHIR_TENANT_ID", "")
CLIENT_ID = os.environ.get("AZURE_FHIR_CLIENT_ID", "")
CLIENT_SECRET = os.environ.get("AZURE_FHIR_CLIENT_SECRET", "")

_token_cache: dict = {"token": None, "expires_at": 0}


def _get_access_token() -> str:
    """Fetch and cache an Azure AD access token for the FHIR scope."""
    now = time.time()
    if _token_cache["token"] and now < _token_cache["expires_at"] - 60:
        return _token_cache["token"]

    url = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token"
    data = {
        "grant_type": "client_credentials",
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "scope": f"{FHIR_BASE}/.default",
    }
    resp = httpx.post(url, data=data, timeout=15)
    resp.raise_for_status()
    result = resp.json()
    _token_cache["token"] = result["access_token"]
    _token_cache["expires_at"] = now + result.get("expires_in", 3600)
    return _token_cache["token"]


async def fhir_get(resource: str, params: dict[str, Any] | None = None) -> dict:
    """Execute a FHIR GET request against Azure Health Data Services."""
    token = _get_access_token()
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.get(
            f"{FHIR_BASE}/{resource}",
            params=params,
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/fhir+json",
            },
        )
        resp.raise_for_status()
        return resp.json()


def extract_entries(bundle: dict) -> list[dict]:
    """Extract resource objects from a FHIR Bundle entry list."""
    return [e["resource"] for e in bundle.get("entry", []) if "resource" in e]


async def get_all_pages(resource: str, params: dict) -> list[dict]:
    """Follow FHIR pagination to collect all matching resources."""
    resources = []
    params = {**params, "_count": 1000}
    bundle = await fhir_get(resource, params)
    resources.extend(extract_entries(bundle))

    while True:
        next_url = next(
            (l["url"] for l in bundle.get("link", []) if l.get("relation") == "next"),
            None,
        )
        if not next_url:
            break
        token = _get_access_token()
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.get(
                next_url,
                headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/fhir+json",
                },
            )
            resp.raise_for_status()
            bundle = resp.json()
        resources.extend(extract_entries(bundle))

    return resources
