# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - None
# Comments: None
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
"""Metric name → performance key mapping via the metric_mappings DB table."""

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, text
from models.mapping import MetricMapping

_cache: list[tuple[str, str, str, int]] | None = None


async def load_mappings(db: AsyncSession) -> list[tuple[str, str, str, int]]:
    """Load active mappings from DB, ordered by priority descending.

    Returns list of (pattern, performance_key, match_type, priority).
    Cached in memory after first load — restart API to pick up new mappings.
    """
    global _cache
    if _cache is not None:
        return _cache
    result = await db.execute(
        select(MetricMapping)
        .where(MetricMapping.active == True)
        .order_by(MetricMapping.priority.desc())
    )
    mappings = result.scalars().all()
    _cache = [(m.pattern, m.performance_key, m.match_type, m.priority) for m in mappings]
    return _cache


async def infer_performance_key(metric_name: str, db: AsyncSession) -> str:
    """Match a metric name against DB patterns and return the performance key.

    Uses case-insensitive substring matching. Returns 'unknown' if no match found.
    Higher-priority patterns are checked first.
    """
    mappings = await load_mappings(db)
    name_lower = metric_name.lower()
    for pattern, performance_key, match_type, _ in mappings:
        if match_type == "exact" and name_lower == pattern.lower():
            return performance_key
        if match_type == "contains" and pattern.lower() in name_lower:
            return performance_key
    return "unknown"


def clear_mapping_cache() -> None:
    """Invalidate the in-memory mapping cache. Call after updating metric_mappings table."""
    global _cache
    _cache = None
