# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-03
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - Added docstrings
# Comments:
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
"""
FHIR metric computation engine.

Each function returns:
  {rate, numerator_count, denominator_count}

Only aggregated counts leave this module — no patient IDs upstream.
"""

from datetime import date, timedelta
from .fhir_client import get_all_pages

TODAY = date.today()

# Lookback windows matching HEDIS specs
ONE_YEAR_AGO   = str(TODAY - timedelta(days=365))
TWO_YEARS_AGO  = str(TODAY - timedelta(days=730))
THREE_YEARS_AGO = str(TODAY - timedelta(days=1095))
TEN_YEARS_AGO  = str(TODAY - timedelta(days=3650))


def _rate(numerator: int, denominator: int) -> float | None:
    return round(numerator / denominator * 100, 2) if denominator else None


def _dob_range(min_age: int, max_age: int) -> tuple[str, str]:
    return (
        str(TODAY.replace(year=TODAY.year - max_age)),
        str(TODAY.replace(year=TODAY.year - min_age)),
    )


async def bp_control() -> dict:
    """Hypertension: BP Control (<140/90). HEDIS CBP. ICD-10: I10. LOINC: 8480-6, 8462-4."""
    # Synthea stores conditions as SNOMED CT; include ICD-10 for real-world EHRs
    patients = await get_all_pages("Condition", {
        "code": "http://snomed.info/sct|59621000,http://snomed.info/sct|38341003,http://hl7.org/fhir/sid/icd-10-cm|I10",
        "_count": 1000,
    })
    patient_ids = list({
        c.get("subject", {}).get("reference", "").split("/")[-1]
        for c in patients
        if c.get("subject", {}).get("reference")
    })
    denominator = len(patient_ids)
    if not denominator:
        return {"rate": None, "numerator_count": 0, "denominator_count": 0}

    observations = await get_all_pages("Observation", {
        "code": "55284-4,8480-6,8462-4",
        "date": f"ge{ONE_YEAR_AGO}",
        "_count": 1000,
    })

    systolic: dict[str, float] = {}
    diastolic: dict[str, float] = {}
    for obs in observations:
        pid = obs.get("subject", {}).get("reference", "").split("/")[-1]
        if pid not in patient_ids:
            continue
        # Handle component-based BP observations
        components = obs.get("component", [])
        for comp in components:
            code = comp.get("code", {}).get("coding", [{}])[0].get("code", "")
            value = comp.get("valueQuantity", {}).get("value")
            if value is None:
                continue
            if code == "8480-6" and pid not in systolic:
                systolic[pid] = value
            elif code == "8462-4" and pid not in diastolic:
                diastolic[pid] = value
        # Also handle top-level valueQuantity
        code = obs.get("code", {}).get("coding", [{}])[0].get("code", "")
        value = obs.get("valueQuantity", {}).get("value")
        if value is not None:
            if code == "8480-6" and pid not in systolic:
                systolic[pid] = value
            elif code == "8462-4" and pid not in diastolic:
                diastolic[pid] = value

    numerator = sum(
        1 for pid in patient_ids
        if systolic.get(pid, 999) < 140 and diastolic.get(pid, 999) < 90
    )
    return {"rate": _rate(numerator, denominator), "numerator_count": numerator, "denominator_count": denominator}


async def diabetes_a1c_control() -> dict:
    """Diabetes: A1C Control (<8%). HEDIS HbA1c. ICD-10: E11. LOINC: 4548-4."""
    # Synthea stores diabetes as SNOMED CT; include ICD-10 for real-world EHRs
    conditions = await get_all_pages("Condition", {
        "code": "http://snomed.info/sct|44054006,http://snomed.info/sct|73211009,http://hl7.org/fhir/sid/icd-10-cm|E11",
        "_count": 1000,
    })
    patient_ids = list({
        c.get("subject", {}).get("reference", "").split("/")[-1]
        for c in conditions
        if c.get("subject", {}).get("reference")
    })
    denominator = len(patient_ids)
    if not denominator:
        return {"rate": None, "numerator_count": 0, "denominator_count": 0}

    observations = await get_all_pages("Observation", {
        "code": "4548-4",
        "date": f"ge{ONE_YEAR_AGO}",
        "_count": 1000,
    })

    latest_a1c: dict[str, float] = {}
    for obs in observations:
        pid = obs.get("subject", {}).get("reference", "").split("/")[-1]
        if pid not in patient_ids:
            continue
        value = obs.get("valueQuantity", {}).get("value")
        if value is not None and pid not in latest_a1c:
            latest_a1c[pid] = value

    numerator = sum(1 for pid in patient_ids if latest_a1c.get(pid, 999) < 8.0)
    return {"rate": _rate(numerator, denominator), "numerator_count": numerator, "denominator_count": denominator}


async def breast_cancer_screening() -> dict:
    """Breast cancer screening. HEDIS BCS. Women 50-74. Last 2 years."""
    dob_min, dob_max = _dob_range(50, 74)
    patients = await get_all_pages("Patient", {
        "gender": "female",
        "birthdate": f"ge{dob_min}",
        "_count": 1000,
    })
    patients = [p for p in patients if p.get("birthDate", "9999") <= dob_max]
    denominator = len(patients)
    if not denominator:
        return {"rate": None, "numerator_count": 0, "denominator_count": 0}

    procedures = await get_all_pages("Procedure", {
        "code": "77067,24604007",
        "date": f"ge{TWO_YEARS_AGO}",
        "_count": 1000,
    })
    screened = {p.get("subject", {}).get("reference", "").split("/")[-1] for p in procedures}
    numerator = sum(1 for p in patients if p["id"] in screened)
    return {"rate": _rate(numerator, denominator), "numerator_count": numerator, "denominator_count": denominator}


async def colorectal_screening() -> dict:
    """Colorectal cancer screening. HEDIS COL. Ages 45-75. Last 10 years."""
    dob_min, dob_max = _dob_range(45, 75)
    patients = await get_all_pages("Patient", {
        "birthdate": f"ge{dob_min}",
        "_count": 1000,
    })
    patients = [p for p in patients if p.get("birthDate", "9999") <= dob_max]
    denominator = len(patients)
    if not denominator:
        return {"rate": None, "numerator_count": 0, "denominator_count": 0}

    procedures = await get_all_pages("Procedure", {
        "code": "45378,73761001",
        "date": f"ge{TEN_YEARS_AGO}",
        "_count": 1000,
    })
    screened = {p.get("subject", {}).get("reference", "").split("/")[-1] for p in procedures}
    numerator = sum(1 for p in patients if p["id"] in screened)
    return {"rate": _rate(numerator, denominator), "numerator_count": numerator, "denominator_count": denominator}


async def annual_wellness_visit() -> dict:
    """Annual Wellness Visit. Last 12 months."""
    encounters = await get_all_pages("Encounter", {
        "date": f"ge{ONE_YEAR_AGO}",
        "_count": 1000,
    })
    # Synthea uses encounter type codes — match wellness/preventive visits
    awv_types = {"wellness", "preventive", "annual", "G0438", "G0439"}
    patients_with_awv = set()
    for e in encounters:
        type_text = str(e.get("type", [{}])[0].get("text", "")).lower()
        type_code = e.get("type", [{}])[0].get("coding", [{}])[0].get("code", "")
        if any(t in type_text for t in awv_types) or type_code in awv_types:
            pid = e.get("subject", {}).get("reference", "").split("/")[-1]
            patients_with_awv.add(pid)

    all_patients = await get_all_pages("Patient", {"_count": 1000})
    denominator = len(all_patients)
    numerator = sum(1 for p in all_patients if p["id"] in patients_with_awv)
    return {"rate": _rate(numerator, denominator), "numerator_count": numerator, "denominator_count": denominator}


async def depression_screening() -> dict:
    """Depression screening. PHQ-9. LOINC: 44249-1. Last 12 months."""
    observations = await get_all_pages("Observation", {
        "code": "44249-1",
        "date": f"ge{ONE_YEAR_AGO}",
        "_count": 1000,
    })
    screened = {o.get("subject", {}).get("reference", "").split("/")[-1] for o in observations}
    all_patients = await get_all_pages("Patient", {"_count": 1000})
    denominator = len(all_patients)
    numerator = sum(1 for p in all_patients if p["id"] in screened)
    return {"rate": _rate(numerator, denominator), "numerator_count": numerator, "denominator_count": denominator}


async def ed_utilization() -> dict:
    """ED utilization. Emergency encounters last 12 months per 1000 members."""
    ed_encounters = await get_all_pages("Encounter", {
        "class": "EMER",
        "date": f"ge{ONE_YEAR_AGO}",
        "_count": 1000,
    })
    all_patients = await get_all_pages("Patient", {"_count": 1000})
    denominator = len(all_patients)
    numerator = len(ed_encounters)
    rate = round(numerator / denominator * 1000, 1) if denominator else None
    return {"rate": rate, "numerator_count": numerator, "denominator_count": denominator}


METRIC_REGISTRY = {
    "bp_control": bp_control,
    "diabetes_a1c_control": diabetes_a1c_control,
    "breast_cancer_screening": breast_cancer_screening,
    "colorectal_screening": colorectal_screening,
    "annual_wellness_visit": annual_wellness_visit,
    "depression_screening": depression_screening,
    "ed_utilization": ed_utilization,
}


async def compute_all() -> dict[str, dict]:
    results = {}
    for key, fn in METRIC_REGISTRY.items():
        try:
            results[key] = await fn()
        except Exception as e:
            results[key] = {"error": str(e), "rate": None, "numerator_count": 0, "denominator_count": 0}
    return results
