# -----------------------------------------------------------
# AI-GENERATED CODE — REVIEW REQUIRED
# Generated by: Claude Sonnet 4.6
# Date generated: 2026-06-04
#
# Reviewer: Tucker Paron
# Review date: 2026-06-04
# Changes made during review:
#   - Created this in liu of hardcoded mapping function (best code practices)
# Comments:
#
# Sign-off: Tucker Paron
# -----------------------------------------------------------
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, Boolean, Integer
from .base import Base


class MetricMapping(Base):
    """Maps extracted metric name patterns to canonical FHIR performance keys.

    Stored in DB so new mappings can be added without a code deploy.
    Checked in priority order — higher priority wins on overlapping patterns.
    """

    __tablename__ = "metric_mappings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    pattern: Mapped[str] = mapped_column(String(255), nullable=False)
    performance_key: Mapped[str] = mapped_column(String(100), nullable=False)
    match_type: Mapped[str] = mapped_column(String(20), nullable=False, default="contains")
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
